runtime: python311
instance_class: F1
entrypoint: gunicorn --bind :$PORT --workers 2 backend.wsgi

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /static
  static_dir: staticfiles
- url: /media
  static_dir: media
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
