version: "3.3"

services:
  db:
    image: postgres:14.5-bullseye
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dzskills
      - POSTGRES_USER=spounka
      - POSTGRES_PASSWORD=pass123
    ports:
      - "5432:5432"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    #    command: gunicorn backend.wsgi --bind 0.0.0.0:8000 --workers 2
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=dzskills
      - POSTGRES_USER=spounka
      - POSTGRES_PASSWORD=pass123
    depends_on:
      - db

