# Generated by Django 4.1.7 on 2023-03-18 20:11

import course_buying.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_buying', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.FileField(upload_to=course_buying.models.get_payment_upload_path),
        ),
    ]
