# Generated by Django 4.1.7 on 2023-04-10 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course_buying', '0002_alter_payment_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_issued',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
