# Generated by Django 4.1.7 on 2023-04-10 22:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course_buying', '0003_alter_order_date_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_issued',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
