# Generated by Django 4.2.2 on 2023-07-18 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="user",
        ),
        migrations.DeleteModel(
            name="Report",
        ),
    ]
