# Generated by Django 4.2.2 on 2023-07-18 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0003_remove_messagefile_message_delete_message_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Conversation",
        ),
    ]
