# Generated by Django 4.2.2 on 2023-07-18 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0006_alter_conversation_recipient"),
        ("support", "0004_delete_conversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="conversation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="messaging.conversation",
            ),
        ),
    ]
