# Generated by Django 4.1.7 on 2023-05-22 10:09

import admin_dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_usage_count', models.PositiveIntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=admin_dashboard.models.receipt_upload_dir)),
                ('count', models.PositiveIntegerField(default=0)),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
    ]
