# Generated by Django 4.1.7 on 2023-06-02 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_certificatetemplate_chosenteacher_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminconfig',
            name='certificate_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='admin_dashboard.certificatetemplate'),
        ),
    ]
