# Generated by Django 4.1.7 on 2023-06-02 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_alter_landingpageimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageimage',
            name='config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.adminconfig'),
        ),
    ]
