# Generated by Django 4.2.2 on 2023-07-24 07:13

import admin_dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_dashboard", "0008_delete_chosenteacher_alter_landingpageimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="description",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AddField(
            model_name="comments",
            name="full_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="comments",
            name="image",
            field=models.ImageField(
                null=True, upload_to=admin_dashboard.models.get_rating_image_upload_dir
            ),
        ),
        migrations.AddField(
            model_name="comments",
            name="rating",
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
