# Generated by Django 4.2.2 on 2023-07-24 07:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_dashboard", "0009_comments_description_comments_full_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="LandingPageRating",
        ),
    ]
