# Generated by Django 4.1.7 on 2023-03-11 09:46

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_chapter_course_alter_chaptervideo_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='presentation_file',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.get_course_file_upload_directory),
        ),
    ]
