# Generated by Django 4.1.7 on 2023-03-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_presentation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('pend', 'Pending'), ('acc', 'Accepted'), ('ref', 'Refused')], default='pend', max_length=30),
        ),
    ]
