# Generated by Django 4.1.7 on 2023-03-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
