# Generated by Django 4.1.7 on 2023-03-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_duration_course_used_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default='Arabic', max_length=30),
        ),
    ]
