# Generated by Django 4.1.7 on 2023-03-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_rename_hastags_course_hashtags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChapterVideo',
            new_name='Video',
        ),
    ]
