# Generated by Django 4.1.7 on 2023-03-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_rename_chaptervideo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(default='', max_length=10),
        ),
    ]
