# Generated by Django 4.1.7 on 2023-04-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_video_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('pend', 'Pending'), ('app', 'Approved'), ('ref', 'Refused')], default='pend', max_length=30),
        ),
    ]
