# Generated by Django 4.1.7 on 2023-04-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_chapter_options_alter_video_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('pend', 'Pending'), ('app', 'Approved'), ('rej', 'Rejected')], default='pend', max_length=30),
        ),
    ]
