# Generated by Django 4.1.7 on 2023-04-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='locked',
            field=models.BooleanField(default=True),
        ),
    ]
