# Generated by Django 4.1.7 on 2023-04-08 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0018_chapter_locked_video_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='video',
            name='locked',
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_video_index', models.SmallIntegerField(default=0)),
                ('last_chapter_index', models.SmallIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
