# Generated by Django 4.1.7 on 2023-04-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_remove_chapter_locked_remove_video_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
