# Generated by Django 4.1.7 on 2023-04-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_studentprogress_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='progress_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
