# Generated by Django 4.1.7 on 2023-05-12 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='hashtags',
        ),
    ]
