# Generated by Django 4.1.7 on 2023-05-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_remove_course_course_level_remove_course_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hashtags',
            field=models.ManyToManyField(to='courses.hashtag'),
        ),
    ]
