# Generated by Django 4.1.7 on 2023-05-13 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_rename_level_course_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.level'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hashtags',
            field=models.ManyToManyField(related_name='courses', to='courses.hashtag'),
        ),
    ]
