# Generated by Django 4.1.7 on 2023-05-13 23:16

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_alter_category_options_alter_course_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to=courses.models.get_category_upload_dir),
        ),
    ]
