# Generated by Django 4.1.7 on 2023-05-31 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseQuizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='QuizzQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=200)),
                ('is_correct_answer', models.BooleanField(default=False)),
                ('quizz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.coursequizz')),
            ],
        ),
    ]
