# Generated by Django 4.1.7 on 2023-05-31 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_coursequizz_quizzquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursequizz',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quizz', to='courses.course'),
        ),
    ]
