# Generated by Django 4.2.2 on 2023-06-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0037_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="average_rating",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
