# Generated by Django 4.2.2 on 2023-06-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0039_alter_chapter_average_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="average_rating",
            field=models.FloatField(default=0),
        ),
    ]
