# Generated by Django 4.2.2 on 2023-06-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0040_course_average_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
