# Generated by Django 4.2.2 on 2023-06-21 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0041_alter_rating_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["-average_rating"]},
        ),
    ]
