# Generated by Django 4.2.2 on 2023-06-22 22:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0042_alter_course_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="QuizzAnswer",
            new_name="QuizzChoice",
        ),
    ]
