# Generated by Django 4.2.2 on 2023-07-13 16:29

import courses.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0044_alter_quizzchoice_question_studentattempt_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="video",
            name="presentation_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=courses.upload_paths.get_video_upload_directory,
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=courses.upload_paths.get_video_upload_directory,
            ),
        ),
    ]
