# Generated by Django 4.2.2 on 2023-07-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0045_remove_chapter_thumbnail_video_presentation_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("pend", "Pending"),
                    ("app", "Approved"),
                    ("rej", "Rejected"),
                    ("edi", "To Revise"),
                ],
                default="pend",
                max_length=30,
            ),
        ),
    ]
