# Generated by Django 4.2.2 on 2023-07-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0046_alter_course_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="state",
            field=models.CharField(
                choices=[
                    ("paused", "Paused"),
                    ("blocked", "Blocked"),
                    ("running", "Running"),
                ],
                default="running",
                max_length=30,
            ),
        ),
    ]
