# Generated by Django 4.2.2 on 2023-07-20 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0047_course_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprogress",
            name="disabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="studentprogress",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
