# Generated by Django 4.1.7 on 2023-02-27 22:48

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=authentication.models.get_image_directory),
        ),
    ]
