# Generated by Django 4.2.2 on 2023-06-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AddField(
            model_name="user",
            name="nationality",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AddField(
            model_name="user",
            name="speciality",
            field=models.CharField(default="", max_length=300),
        ),
    ]
