# Generated by Django 4.2.2 on 2023-06-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_user_description_user_nationality_user_speciality"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="average_rating",
            field=models.FloatField(default=0.0),
        ),
    ]
