# Generated by Django 4.2.2 on 2023-06-22 12:34

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0006_user_average_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="average_rating",
            field=models.FloatField(default=0.0, verbose_name="Average Rating"),
        ),
        migrations.AlterField(
            model_name="user",
            name="description",
            field=models.CharField(
                default="", max_length=300, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nationality",
            field=models.CharField(
                default="", max_length=300, verbose_name="Nationality"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                null=True,
                upload_to=authentication.models.get_image_directory,
                verbose_name="Profile Image",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="speciality",
            field=models.CharField(
                default="", max_length=300, verbose_name="Speciality"
            ),
        ),
    ]
