# Generated by Django 4.2.2 on 2023-07-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0007_alter_user_average_rating_alter_user_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_favorite",
            field=models.BooleanField(default=False, verbose_name="Favorite"),
        ),
    ]
