# Generated by Django 4.2.2 on 2023-07-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0008_user_is_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="facebook_link",
            field=models.CharField(blank=True, default="", max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="instagram_link",
            field=models.CharField(blank=True, default="", max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin_link",
            field=models.CharField(blank=True, default="", max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="twitter_link",
            field=models.CharField(blank=True, default="", max_length=300, null=True),
        ),
    ]
