# Generated by Django 4.1.7 on 2023-06-05 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagefile',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='messaging.message'),
        ),
    ]
