# Generated by Django 4.2.2 on 2023-07-18 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("messaging", "0005_rename_teacher_conversation_recipient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation_recipient",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
