# Generated by Django 4.1.7 on 2023-03-18 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(null=True, upload_to=user_profile.models.get_image_directory)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('nationality', models.CharField(blank=True, max_length=30, null=True)),
                ('speciality', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('fb', 'Facebook'), ('ig', 'Instagram'), ('li', 'LinkedIn'), ('be', 'Behance'), ('tw', 'Twitter')], default='fb', max_length=10)),
                ('url', models.URLField(max_length=300)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='user_profile.userprofile')),
            ],
        ),
    ]
