# Generated by Django 4.1.7 on 2023-03-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_language'),
        ('student', '0002_student_courses_studentprogression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='courses.course'),
        ),
    ]
