# Generated by Django 4.1.7 on 2023-03-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogression',
            name='chapter',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprogression',
            name='video',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
