# Generated by Django 4.1.7 on 2023-04-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studentprogression_chapter_studentprogression_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProgression',
        ),
    ]
