# Generated by Django 4.2.2 on 2023-06-22 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="commentor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Commentor",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.CharField(default="", max_length=300, verbose_name="Content"),
        ),
    ]
