# Generated by Django 4.2.2 on 2023-08-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
