# Generated by Django 4.2.2 on 2023-08-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_balance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moneyrequest",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
